### ISSUE TITLE
Защита от повторного голосования

### ISSUE THREAD

**Issue by justbekami** [me6iaton/VoteForms#1]
На мой взгляд, основное из пожеланий на текущий момент - возможность привязывать голосования к сессиям/кукам и/или ставить условие, для голосования только авторизованных пользователей, дабы не было возможности накручивать рейтинги.

//Также, было бы здорово выставлять возможный формат подсчета итогового значения - процентами, рейтингом с дробным значением  тд.

**Comment by me6iaton** [comment]
Голосование сейчас возможно только авторизованным пользователям... http://ms2form.me6iaton.ru/voteforms/resource1.html
